# Generated by Django 4.2.3 on 2023-07-11 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booklet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_number', models.CharField(max_length=9)),
                ('cf', models.CharField(max_length=16)),
                ('email', models.EmailField(max_length=254)),
                ('total_exams', models.IntegerField(default=0)),
                ('total_credits', models.IntegerField(default=0)),
                ('setup_status', models.IntegerField(default=0)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('credits', models.IntegerField(default=0)),
                ('year', models.CharField(choices=[('First', 'First'), ('Second', 'Second'), ('Third', 'Third')], default='First', max_length=10)),
                ('semester', models.CharField(choices=[('First', 'First'), ('Second', 'Second')], default='First', max_length=10)),
                ('completion_date', models.DateField(null=True)),
                ('completion_grade', models.IntegerField(null=True)),
                ('cum_laude', models.BooleanField(default=False)),
                ('booklet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booklet.booklet')),
            ],
        ),
    ]
