# Generated by Django 4.2.3 on 2023-07-11 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booklet',
            name='cf',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='booklet',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='booklet',
            name='personal_number',
            field=models.CharField(max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='booklet',
            name='setup_status',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='booklet',
            name='total_credits',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='booklet',
            name='total_exams',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
