# Generated by Django 4.2.3 on 2023-07-11 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklet', '0002_alter_booklet_cf_alter_booklet_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booklet',
            name='cf',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='booklet',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='booklet',
            name='personal_number',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
